{
 "title": "Self-Design Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "label": "interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(mysql_up,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "MySQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "當前運行狀況(1：正常;0：不正常)",
   "type": "stat",
   "description": "表示是否停機",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_max_connections",
     "legendFormat": "Max"
    },
    {
     "expr": "mysql_global_status_threads_connected{instance=\"localhost:9104\"}",
     "legendFormat": "Connected"
    },
    {
     "expr": "mysql_global_status_threads_running{instance=\"localhost:9104\"}",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Questions ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "increase(mysql_global_status_questions{job=\"mysql\", instance=\"localhost:9104\"}[$__rate_interval])",
     "legendFormat": "Times"
    }
   ]
  },
  {
   "title": "SQL Commands",
   "type": "stat",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(mysql_global_status_commands_total{command=\"select\", instance=\"localhost:9104\"}[$__rate_interval])",
     "legendFormat": "Select"
    },
    {
     "expr": "increase(mysql_global_status_commands_total{command=\"delete\", instance=\"localhost:9104\"}[$__rate_interval])",
     "legendFormat": "Delete"
    },
    {
     "expr": "increase(mysql_global_status_commands_total{command=\"update\", instance=\"localhost:9104\"}[$__rate_interval])",
     "legendFormat": "Update"
    },
    {
     "expr": "increase(mysql_global_status_commands_total{command=\"insert\", instance=\"localhost:9104\"}[$__rate_interval])",
     "legendFormat": "Insert"
    }
   ]
  },
  {
   "title": "已運行時間",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_uptime{instance=\"localhost:9104\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "慢查詢(過去一天)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_slow_queries{instance=\"localhost:9104\"}",
     "legendFormat": "Number"
    }
   ]
  },
  {
   "title": "連接錯誤總次數(過去一天)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mysql_global_status_connection_errors_total{instance=\"localhost:9104\"})",
     "legendFormat": "Errors"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  { "title": "Event Loop", "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 } },
  {
   "title": "Request Times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "nodejs_active_requests_total{job=\"Meal_Order\"}",
     "legendFormat": "Request Time"
    }
   ]
  }
 ]
}