apiVersion: apps/v1
kind: Deployment
metadata:
  name: meal-order-frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meal-order-frontend
  template:
    metadata:
      labels:
        app: meal-order-frontend
    spec:
      containers:
      - name: meal-order-frontend
        image: acrmealorderimages.azurecr.io/meal-order-frontend:latest
        # resources:
        #   limits:
        #     memory: "3560Mi"
        #     cpu: "5000m"
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_BACKEND_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REACT_APP_BACKEND_HOST
        - name: REACT_APP_BACKEND_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PORT
        - name: REACT_APP_WS_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REACT_APP_WS_HOST
        - name: REACT_APP_WS_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PORT

---

apiVersion: v1
kind: Service
metadata:
  name: meal-order-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: meal-order-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000